# Generated by Django 4.0 on 2021-12-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_cricao',
            new_name='data_criacao',
        ),
    ]
